---
title: "Emergency DataSet"
output:
  html_document: default
  pdf_document: default
date: "2023-08-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df=read.csv("emergency.csv", stringsAsFactors = TRUE,row.names = 1)
#stringsAsFactors will convert column strings to factor, default false
str(df)
```

```{r}
nrow(df)
ncol(df)
```
```{r}
df$Condition=factor(df$Condition)
contrasts(df$Condition)
```


```{r}
str(df$Condition)
```


```{r}
df$Insurance=as.factor(df$Insurance)
contrasts(df$Insurance)
```
```{r}
str(df$Insurance)
```
```{r}
#this part is important to convert column of strings to column of vector

dfPatient= df=read.csv("emergency.csv", stringsAsFactors = FALSE,row.names = 1)

categorical_cols=c('Condition','Insurance')

dfPatient[,categorical_cols]=lapply(dfPatient[,categorical_cols],as.factor)

str(dfPatient)
```
```{r}
levels(dfPatient$Condition)
```

```{r}
levels(dfPatient$Insurance)

```
```{r}
contrasts(dfPatient$Condition)
```

```{r}
contrasts(dfPatient$Insurance)
```
One hot encoding is done when we used contrasts 

```{r}
dfPatient$Condition=='serious'
print(sum(dfPatient$Condition=='serious'))
```
```{r}
print(mean(dfPatient$Condition=='serious')*100)
```
```{r}
mean(dfPatient$Condition=='good')*100
```
```{r}
mean(dfPatient$Condition=='fair')*100

```

```{r}
mean(dfPatient$Insurance=='insured')*100

```
```{r}
mean(dfPatient$Insurance=='not insured')*100

```
```{r}
mean( dfPatient$Insurance == 'insured' & dfPatient$Condition == 'serious' ) * 100

```

```{r}
mean(dfPatient$Condition == 'serious' & dfPatient$Insurance == 'insured') * 100

```
```{r}
mean(dfPatient[ dfPatient$Insurance=='insured',]$Condition=='serious')*100

```

```{r}
mean(dfPatient[dfPatient$Condition=='serious',]$Insurance=='insured')*100
```
```{r}
mean(dfPatient$Condition == 'serious' & dfPatient$Insurance == 'insured') * 100/mean(dfPatient$Insurance='insured')
```
```{r}
mean(dfPatient$Condition == 'serious' & dfPatient$Insurance == 'insured') * 100/mean(dfPatient$Condition=='serious')
```
```{r}
mean(dfPatient$Insurance=='insured')*100
```

