---
output:
  pdf_document: default
  html_document: default
---
```{r}
#Load the DataSet

dfBat=read.csv("bats.csv")
str(dfBat)
```

```{r}
ncol(dfBat)
nrow(dfBat)
```

```{r}
logical_columns = c("Gene.1", "Gene.2", "Gene.3", "Gene.4", "Gene.5", "Ebola")
dfBat[logical_columns] = lapply(dfBat[logical_columns], as.numeric)
```

# a) What is the chance of a random bat carrying the Ebola virus?
```{r}
TotalEbolaBats = sum(dfBat$Ebola)
totalBats = nrow(dfBat)
EbolaChance = TotalEbolaBats / totalBats
cat("Chance of a random bat carrying Ebola is", EbolaChance)

```
# b)  For each gene, calculate the likelihood that it is expressed in a random bat.

```{r}
likelihood = colMeans(dfBat[, c("Gene.1", "Gene.2", "Gene.3", "Gene.4", "Gene.5")])
dfLikelihood = data.frame(Gene = c("Gene.1", "Gene.2", "Gene.3", "Gene.4", "Gene.5"),Likelihood = likelihood)
print(dfLikelihood)

```


# c) Is the presence or absence of any of the genes indicative of a random bat potentially carrying the Ebola virus?

## Method 1
```{r}
genes = c("Gene.1", "Gene.2", "Gene.3", "Gene.4", "Gene.5")

# Calculate the proportion of bats carrying Ebola for each gene's presence and absence
for (gene in genes) {
  Ebola = mean(dfBat[dfBat[[gene]] == TRUE, "Ebola"])
  NoEbola = mean(dfBat[dfBat[[gene]] == FALSE, "Ebola"])
  
  cat("Gene:", gene, "\n")
  cat("Proportion of bats carrying Ebola with", gene, "present:", Ebola, "\n")
  cat("Proportion of bats carrying Ebola with", gene, "absent:", NoEbola)
  cat( "\n \n")
}
```

## Method 2 we can use Binomial also

```{r}

dfBat$Ebola_numeric = as.numeric(dfBat$Ebola)
model = glm(Ebola_numeric ~ Gene.1 + Gene.2 + Gene.3 + Gene.4 + Gene.5,
             data = dfBat, family = binomial)
summary(model)

```

## Method 3 we can use chi-squared on the Dataset also

```{r}
genes = c("Gene.1", "Gene.2", "Gene.3", "Gene.4", "Gene.5")

for (gene in genes) {
  cross_tab = table(dfBat[[gene]], dfBat$Ebola)
  chi_result = chisq.test(cross_tab)
  
  cat("Chi-squared test for", gene, "and Ebola:\n")
  print(chi_result)
}
```
