---
title: "CourtJudge"
output: html_document
date: "2023-08-07"
---

```{r}
#sampling space

s=c(1,0)

#corresponding possibilities 
p=matrix(nrow = 5,ncol = 2,
         c(0.95,0.95,0.9,0.9,0.8,0.05,.05,.05,.1,.2))

str(p)

sample(s,size=10, replace = TRUE,prob = p[5,] )

#print(p)
```
```{r}
for (p in c(1L:6L)){
    print(p)
}

p=c(1L,'abc',234)
str(p)
```

```{r}
#sampling space

s=c(1,0)

#corresponding possibilities 
p=matrix(nrow = 5,ncol = 2,
         c(0.95,0.95,0.9,0.9,0.8,0.05,.05,.05,.1,.2))

#str(p)

#sample(s,size=10, replace = TRUE,prob = p[5,] )

judgeResult= function(){
    result= numeric(5)
    for (j in c(1:5)) {
     result[j]=sample(s,size = 1,replace = TRUE,prob = p[j,])   
    }
    return(result)
}
replicate(100,judgeResult())
```
```{r}
nsumulations =10000

simulatedData=replicate(nsumulations, judgeResult())
str(simulatedData)
```

```{r}
data=c(1,1,1,0,0)
sum(data)<3

checkEvent= function(data){
    return(sum(data)<3)
}
```

```{r}
apply(simulatedData,2,checkEvent)
```

```{r}
mean (apply(simulatedData,2,checkEvent))
```

